# 识别压缩包类型流程

flow:
  steps:
    # 扫描压缩包
    - name: scan
      dir: archive/base

    # 测试压缩包
    - name: archive
      # 识别模式
      mode: list
      # 识别统计信息 info/list.json
      stat_file_name: list
