name: Publish package to PyPI

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v3
        with:
            enable-cache: true
            github-token: ${{ secrets.GITHUB_TOKEN }}
            version: 'latest'

      - name: Install dependencies
        run: rye sync --no-lock --no-dev

      - name: Build package
        run: rye build

      - name: Twine upgrade
        run: $RYE_HOME/self/bin/pip install twine>=5.1.1

      - name: Publish package
        run: rye publish --token ${{ secrets.PYPI_API_TOKEN }} --yes