name: Publish package to PyPI

on:
  release:
    types: [created]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: "latest"

      - name: Install dependencies
        run: rye sync --no-lock --no-dev

      - name: Update template version
        run: rye run template

      - name: Build release assets
        run: rye run release

      - name: Build package
        run: rye build

      - name: Publish package
        run: rye publish --token ${{ secrets.PYPI_API_TOKEN }} --yes

      - name: Commit and push release changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update release
          file_pattern: "release/template auto_unpack/release.json"
          # disable_globbing: true

      - name: Update release assets
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          omitBodyDuringUpdate: true
          artifacts: "release/dist/*"
          name: "auto-unpack ${{ github.ref_name }}"
