name: Publish Page

on:
  release:
    types: [created]

  workflow_dispatch:

jobs:
  build-page:
    needs:
      - update-examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Cache Python dependencies
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - name: Use cached
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache-mkdocs
          restore-keys: |
            mkdocs-material-

      - name: Install Python dependencies
        run: pip install -r requirements-dev.lock

      - name: Build documentation
        run: mkdocs gh-deploy --force

  update-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v3
        with:
          enable-cache: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: "latest"

      - name: Install dependencies
        run: rye sync --no-lock

      - name: Build examples
        run: rye run examples

      - name: Commit and push examples changes
        uses: stefanzweifel/git-auto-commit-action@v5
        id: auto-commit-action
        with:
          commit_message: Update examples
          file_pattern: examples
