name: Publish package to PyPI

on:
  release:
    types: [created]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v4
        with:
          enable-cache: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: "latest"
          cache-prefix: "cache-publish-package"

      - name: Install dependencies
        run: rye sync --no-lock --no-dev

      - name: Update template version
        run: rye run template

      - name: Build package
        run: rye build

      - name: Twine upgrade
        run: $RYE_HOME/self/bin/pip install twine>=5.1.1

      - name: Publish package
        run: rye publish --token ${{ secrets.PYPI_API_TOKEN }} --yes

      - name: Commit and push template changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update template
          file_pattern: auto_unpack/template
