name: Update schema

on:
  release:
    types: [created]

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v3
        with:
          enable-cache: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: "latest"

      - name: Install dependencies
        run: rye sync --no-lock

      - name: Update schema
        run: rye run schema

      - name: Commit and push schema changes
        uses: stefanzweifel/git-auto-commit-action@v5
        id: auto-commit-action
        with:
          commit_message: 更新 schema
          file_pattern: schema
